# Generated by Django 3.2.5 on 2021-07-26 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coin',
            options={'ordering': ('nome',), 'verbose_name': 'ativo', 'verbose_name_plural': 'ativos'},
        ),
    ]
